[programs.localnet]
stake = "5JqFVkV8QNpm7WpiUkRxrXbDVncRYgdbia8EWDWNrQ62"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/nikhilgupta/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
